name: pluralsight
on:
  #schedule:
  #  - cron: 0 */24 * * *
  workflow_dispatch:
    inputs:
    
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Pluralsight
    steps:
      - uses: actions/checkout@v2
      - name: rclone Install
        run: |
          curl https://rclone.org/install.sh | sudo bash
      - name: rclone Config
        run: |
          mkdir -p ~/.config/rclone
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONFIG_0 }}
          EOF
      - name: rclone Run
        run: |
          rclone copy plural:/ 40:/ --drive-server-side-across-configs --stats=1s --stats-one-line -P --check-first 
